server:
  port: 1111


eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:1111/eureka
spring:
  security:
    user:
      name: feign-server
