server:
  port: 8070
spring:
  application:
    name: param-provider

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:1111/eureka
